In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
# Linear relation of the Yield of Crops with respect to Temperature, Rainfall and Humidity of a Particular Region.
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3

In [4]:
print(kanto_yield_apples)

56.8


In [5]:
print(f"The expected yield of apple in the Kanto Region is {kanto_yield_apples} tons per hectare")

The expected yield of apple in the Kanto Region is 56.8 tons per hectare


In [6]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [7]:
weights = [w1, w2, w3]

In [8]:
def crop_yield(region, weight):
    result = 0
    for w, x in zip(weight, region):
        result += x * w
    return result

In [9]:
crop_yield(kanto, weights)

56.8

In [10]:
crop_yield(johto, weights)

76.9

In [11]:
crop_yield(hoenn, weights)

81.9

<h1>Operations On Numpy</h1>

In [12]:
import numpy as np

In [13]:
kanto = np.array([73, 67, 43])

In [14]:
weights = np.array([w1, w2, w3])

In [15]:
kanto

array([73, 67, 43])

In [43]:
weights

numpy.ndarray

<h3>Numpy has the same behaviour as list when it comes to Indexing.</h3>

In [17]:
weights[0]

0.3

In [18]:
weights[1]

0.2

In [19]:
kanto[2]

43

In [20]:
type(kanto)

numpy.ndarray

In [21]:
type(weights)

numpy.ndarray

<h3>help(np.dot) will give the Documentation of the dot function in the Numpy Library.</h3>

In [22]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    ----------
    a 

<h3>2-D Array Example using np.dot() Function</h3>

In [23]:
a = [[1, 0], [0, 1]]

In [24]:
b = [[4, 1], [2, 2]]

In [25]:
np.dot(a, b)

array([[4, 1],
       [2, 2]])

np.dot() Function

In [26]:
np.dot(kanto, weights)

56.8

np.sum()

In [27]:
kanto

array([73, 67, 43])

In [28]:
weights

array([0.3, 0.2, 0.5])

In [29]:
kanto * weights

array([21.9, 13.4, 21.5])

In [30]:
(kanto * weights).sum()

56.8

In [31]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [32]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1 * x2
result

CPU times: total: 15.6 ms
Wall time: 97.9 ms


833332333333500000

In [33]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 0 ns


-1942957984

Multidimensional Array

In [34]:
climate_data = np.array([[73, 67, 43],
                       [91, 88, 64],
                       [87, 134, 58],
                       [102, 43, 37],
                       [69, 96, 70]])

In [35]:
type(climate_data)

numpy.ndarray

In [42]:
# 2D Array
climate_data.dtype

dtype('int32')

In [37]:
weights

array([0.3, 0.2, 0.5])

In [38]:
weights.shape

(3,)

In [39]:
# 3D Array
arr3 = np.array([
    [[11, 12, 13], 
     [14, 15, 16, 14]], 
    
    [[15, 16, 17], 
     [18, 19, 20]]
                    ])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [ ]:
arr3 = np.array([
    [[11, 12, 13], 
     [14, 15, 16]], 
    
    [[15, 16, 17], 
     [18, 19, 20]]
                    ])

In [ ]:
arr3.shape

In [ ]:
weights.dtype

In [ ]:
climate_data

In [ ]:
climate_data.dtype

In [ ]:
climate_data.shape

In [ ]:
arr3.dtype

In [ ]:
arr3 = np.array([
    [[11, 12, 13], 
     [14, 15, 16]], 
    
    [[15, 16, 17], 
     [18, 19, 18.4]]
                    ])

In [ ]:
arr3.dtype

In [ ]:
arr3

In [ ]:
climate_data

In [ ]:
# Performs Matrix Multiplication of the Matrices
np.matmul(climate_data, weights)

In [ ]:
# Alternative way for Matrix Multiplicaiton using '@' Symbol.
climate_data @ weights

Using CSV files along with Numpy

In [ ]:
from urllib import request

In [ ]:
# request.urlretrieve("link", "path")

In [ ]:
request.urlretrieve(
 'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

In [ ]:
help(np.genfromtxt)

In [ ]:
climate_data = np.genfromtxt('climate.txt', delimiter = ',', skip_header = 1)

In [ ]:
climate_data

In [ ]:
climate_data.shape

In [ ]:
 weights

In [ ]:
yields = climate_data @ weights

In [ ]:
yields

In [ ]:
yields.shape

In [ ]:
yields


In [ ]:
help(np.concatenate)

In [ ]:
help(np.reshape)

In [ ]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis = 1)

In [ ]:
climate_results

In [ ]:
help(np.savetxt)

In [ ]:
np.savetxt('climate_results.txt', 
           climate_results,
           fmt='%.2f',
           header='temperature,rainfall,humidity,yield_apples',
           comments='')

In [ ]:
# Upto this Part for Blog Post on Numpy

<h1>Arithmetic Operations, Broadcasting, Comparison on Arrays</h1> 

In [ ]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [ ]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [ ]:
arr2 + arr3

In [ ]:
 # Additing a Scalar
arr3 + 3

In [ ]:
arr2 - arr3

In [ ]:
arr2 / 2

In [ ]:
arr2 * arr3

In [ ]:
arr3 % 4

In [ ]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [ ]:
arr2.shape

In [ ]:
arr4 = np.array([4, 5, 6, 7])

In [ ]:
arr4.shape

In [ ]:
arr2 + arr4

In [ ]:
# Broadcasting in Numpy means what Numpy does is it replicates the array so in order to do the Arithmetic Operation

In [ ]:
arr4_replicated = np.array([[4, 5, 6, 7],
                           [4, 5, 6, 7],
                           [4, 5, 6, 7]])
# So arr4 is Replicated like this and then the any Arithmetic Operation is performed on the Array

In [ ]:
arr2 + arr4

In [ ]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

In [ ]:
arr2.shape

In [ ]:
arr4 = np.array([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8]])

In [ ]:
arr4.shape

In [ ]:
arr2 + arr4

In [ ]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [ ]:
arr1 == arr2

In [ ]:
(arr1 == arr2).dtype

In [ ]:
arr1 != arr2

In [ ]:
arr1 < arr2

In [ ]:
arr1 > arr2

In [ ]:
# Corresponding Elements are Compared using Comparison Operators

In [ ]:
(arr1 == arr2).sum()
# Give out the Total Number of True comparion in Array1 and Array2.

Array Indexing & Slicing 


In [ ]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [40]:
arr3.shape

NameError: name 'arr3' is not defined

In [ ]:
# Single Element
arr3[1, 1, 2]

In [ ]:
arr3[1, 1, 2].shape

In [ ]:
arr3.dtype

In [ ]:
# Subarray using Ranges
arr3[0:2, 0:1, 0:3] 

In [ ]:
arr3[1]

In [ ]:
arr3[:2, 1]

In [ ]:
# Using too many indices - Error Example
arr3[1,3,2,1]

In [ ]:
# 4x  + 3y = 20
# -5x + 9y = 26

In [ ]:
eqn = np.array([[4, 3], 
                [-5, 9]])

In [ ]:
eqn.dtype

In [ ]:
eqn.shape

In [ ]:
constants = np.array([20, 26])

In [ ]:
constants.shape

In [ ]:
variables = np.array(['x', 'y'])

In [ ]:
variables.dtype

In [ ]:
variables.shape

In [ ]:
# All Zeros
np.zeros((3, 2))

In [ ]:
# All Ones
np.ones((2, 2, 3))

In [ ]:
# Identity Matrix
np.eye(3)

In [ ]:
# Random Vector - Rand function picks Uniform value from 0 to 1
np.random.rand(5)

In [ ]:
# Random MAtrix - Randn Picks up the Value from the gaussian Distribution Value Range - (-2, 2)
np.random.randn(2, 3)

In [ ]:
help(np.random.rand)

In [ ]:
np.full([2, 3], 42)

In [ ]:
# Range with start, end and step
new_arr = np.arange(10, 90, 3)

In [ ]:
new_arr.shape

In [ ]:
new_arr.reshape(3, 3, 3)

In [ ]:
help(np.reshape)

In [ ]:
# Equally Spaced Number in a Range
np.linspace(3, 27, 9)

In [ ]:
new_arr.ndim

In [1]:
# Timestamp - 01:12:16

In [2]:
import os

In [4]:
os.getcwd()

'C:\\Users\\pahir\\Numpy'

In [5]:
os.listdir(".")

['.ipynb_checkpoints',
 'climate.txt',
 'climate_results.txt',
 'data',
 'Hands-on-Numpy.ipynb']

In [9]:
os.makedirs('./data', exist_ok=True)

In [11]:
os.listdir('./data')

[]

In [12]:
from urllib.request import urlretrieve

In [13]:
url1 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans1.txt'
url2 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans2.txt'
url3 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans3.txt'

In [19]:
urlretrieve(url1, "./data/loans1.txt")

('./data/loans1.txt', <http.client.HTTPMessage at 0x1bd4b6ab290>)

In [15]:
urlretrieve(url2, "./data/loans2.txt")

('./data/loans2.txt', <http.client.HTTPMessage at 0x1bd4aa32c90>)

In [17]:
urlretrieve(url3, "./data/loans3.txt")

('./data/loans3.txt', <http.client.HTTPMessage at 0x1bd4b6a9b90>)

In [20]:
os.listdir("./data")

['loans.txt', 'loans1.txt', 'loans2.txt', 'loans3.txt']

In [5]:
with open("./data/loans1.txt", 'r') as file:
    fileContents = file.readlines()

In [6]:
fileContents

['amount,duration,rate,down_payment\n',
 '100000,36,0.08,20000\n',
 '200000,12,0.1,\n',
 '628400,120,0.12,100000\n',
 '4637400,240,0.06,\n',
 '42900,90,0.07,8900\n',
 '916000,16,0.13,\n',
 '45230,48,0.08,4300\n',
 '991360,99,0.08,\n',
 '423000,27,0.09,47200']

In [10]:
def parse_header(file):
    return file[0].strip().split(',')

In [26]:
def parse_line(fileValues):
    values = []
    for data in fileValues.strip().split(','):
        if data == "":
            values.append(0)
        else:
            values.append(float(data))
    return values

In [27]:
def create_dict(fileValues, headers):
    loanDict = {}
    for data, header in zip(fileValues, headers):
        loanDict[header] = data
    return loanDict

In [28]:
headers = parse_header(fileContents)

In [29]:
values = parse_line(fileContents[1])

In [33]:
loan_dict = create_dict(values, headers)

In [34]:
loan_dict

{'amount': 100000.0, 'duration': 36.0, 'rate': 0.08, 'down_payment': 20000.0}

In [59]:
def read_csv(file):
    values = []
    header = file[0].strip().split(',')
    for data in file[1:]:
        value = parse_line(data)
        values.append(create_dict(value, header))
    return values